/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas.Informacion;

import ventanas.Clases.Parques;

/**
 *
 * @author Steve
 */
public class Informacion_PParaiso extends javax.swing.JFrame {

    /**
     * Creates new form Paraiso
     */
    public Informacion_PParaiso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Parques/ParqueParaiso.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 20, 560, 220);

        btnVolver.setBackground(new java.awt.Color(76, 84, 84));
        btnVolver.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("VOLVER");
        btnVolver.setBorder(null);
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setFocusPainted(false);
        btnVolver.setMaximumSize(new java.awt.Dimension(100, 40));
        btnVolver.setMinimumSize(new java.awt.Dimension(100, 40));
        btnVolver.setOpaque(true);
        btnVolver.setPreferredSize(new java.awt.Dimension(100, 40));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver);
        btnVolver.setBounds(347, 436, 100, 40);

        jTextPane1.setBackground(new java.awt.Color(153, 153, 0));
        jTextPane1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTextPane1.setText("El Parque de El Paraíso ubicado en el área de Gapal, junto a las sedes de las Facultades de Ciencias Médicas y Odontología de la Universidad de Cuenca, es sin duda el parque atractivo más grande de Cuenca. Dispone en efecto de canchas para prácticas deportivas de niños y jóvenes, de juegos infantiles, una laguna artificial provista de pequeños botes plásticos utilizados para remar y navegar, hay un estanque o un pequeño lago con patos senderos y sitios para acampar, también encontramos  senderos para bicicletas, cuenta con abundante vegetación, árboles grandes de eucaliptos y de otras especies forestales, además sus llamativos senderos por donde la gente puede pasear y recorrer los bordes del parque. El Paraíso, el parque más grande de Cuenca, es un atractivo turístico de la ciudad y el Azuay., inaugurado el 19 de marzo del 2003; los visitantes pueden acceder de manera gratuita, de lunes a domingo con restricción de horario nocturno, se permite la estancia dentro de este espacio solo hasta las 21H00. Tiene una extensión de 17 hectáreas, brinda al público en general hermosos muelles de ingreso y un islote en el centro de la laguna. Conocer este hermoso lugar es indispensable, disfrutar de coloridos paisajes y exuberante vegetación nos traslada a un espacio de tranquilidad. Caminar detenidamente y observar múltiples perspectivas llenan de emoción y satisfacción, logrando equilibrio y armonía dentro de nosotros. ");
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(63, 249, 680, 148);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Parques/ParqueFondo.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 500);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        btnVolver.setBackground(new java.awt.Color(30, 168, 150));
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        btnVolver.setBackground(new java.awt.Color(76, 84, 84));
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Parques parque= new Parques();
        parque.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
